Disable qtwebkit therefore disable qupzilla too
Can't build qtwebkit anymore, here's the error:

ln -s libQt5WebKitWidgets.so.5.2.0 libQt5WebKitWidgets.so
ln -s libQt5WebKitWidgets.so.5.2.0 libQt5WebKitWidgets.so.5
ln -s libQt5WebKitWidgets.so.5.2.0 libQt5WebKitWidgets.so.5.2
rm -f ../lib/libQt5WebKitWidgets.so.5.2.0
rm -f ../lib/libQt5WebKitWidgets.so
rm -f ../lib/libQt5WebKitWidgets.so.5
rm -f ../lib/libQt5WebKitWidgets.so.5.2
mv -f libQt5WebKitWidgets.so.5.2.0  ../lib/
mv -f libQt5WebKitWidgets.so ../lib/
mv -f libQt5WebKitWidgets.so.5 ../lib/
mv -f libQt5WebKitWidgets.so.5.2 ../lib/
{ test -z "../lib/" || cd "../lib/"; } && test $(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index ." -ex quit 'libQt5WebKitWidgets.so.5.2.0' && test -f libQt5WebKitWidgets.so.5.2.0.gdb-index && objcopy --add-section '.gdb_index=libQt5WebKitWidgets.so.5.2.0.gdb-index' --set-section-flags '.gdb_index=readonly' 'libQt5WebKitWidgets.so.5.2.0' 'libQt5WebKitWidgets.so.5.2.0' && rm -f libQt5WebKitWidgets.so.5.2.0.gdb-index || true
make[2]: Leaving directory `/mauibuild/source/qtwebkit/_build/Source'
cd WebKit2/ && ( test -e Makefile.WebProcess || /usr/bin/qmake /mauibuild/source/qtwebkit/_build/Source/WebKit2/WebProcess.pro -o Makefile.WebProcess ) && make -f Makefile.WebProcess
make[2]: Entering directory `/mauibuild/source/qtwebkit/_build/Source/WebKit2'
g++ -c -Wall -Wextra -Wreturn-type -fno-strict-aliasing -Wchar-subscripts -Wformat-security -Wreturn-type -Wno-unused-parameter -Wno-sign-compare -Wno-switch -Wno-switch-enum -Wundef -Wmissing-noreturn -Winit-self -O2 -pipe -g -m64 -march=x86-64 -mtune=generic -Wno-c++0x-compat -g -fno-exceptions -D_REENTRANT -fPIE -MD -DQT_NO_XKB -DHAVE_WEBKIT1 -DBUILDING_QT__=1 -DENABLE_3D_RENDERING=1 -DENABLE_BLOB=1 -DENABLE_CHANNEL_MESSAGING=1 -DENABLE_CSS_BOX_DECORATION_BREAK=1 -DENABLE_CSS_COMPOSITING=1 -DENABLE_CSS_EXCLUSIONS=1 -DENABLE_CSS_FILTERS=1 -DENABLE_CSS_IMAGE_SET=1 -DENABLE_CSS_REGIONS=1 -DENABLE_CSS_STICKY_POSITION=1 -DENABLE_DATALIST_ELEMENT=1 -DENABLE_DETAILS_ELEMENT=1 -DENABLE_FAST_MOBILE_SCROLLING=1 -DENABLE_FILTERS=1 -DENABLE_FTPDIR=1 -DENABLE_FULLSCREEN_API=1 -DENABLE_GESTURE_EVENTS=1 -DENABLE_ICONDATABASE=1 -DENABLE_IFRAME_SEAMLESS=1 -DENABLE_INPUT_TYPE_COLOR=1 -DENABLE_INSPECTOR=1 -DENABLE_INSPECTOR_SERVER=1 -DENABLE_JAVASCRIPT_DEBUGGER=1 -DENABLE_LEGACY_NOTIFICATIONS=1 -DENABLE_LEGACY_VIEWPORT_ADAPTION=1 -DENABLE_LEGACY_VENDOR_PREFIXES=1 -DENABLE_LINK_PREFETCH=1 -DENABLE_METER_ELEMENT=1 -DENABLE_MHTML=1 -DENABLE_MUTATION_OBSERVERS=1 -DENABLE_NOTIFICATIONS=1 -DENABLE_PAGE_VISIBILITY_API=1 -DENABLE_PROGRESS_ELEMENT=1 -DENABLE_RESOLUTION_MEDIA_QUERY=1 -DENABLE_REQUEST_ANIMATION_FRAME=1 -DENABLE_SHARED_WORKERS=1 -DENABLE_SMOOTH_SCROLLING=1 -DENABLE_SQL_DATABASE=1 -DENABLE_SVG=1 -DENABLE_SVG_FONTS=1 -DENABLE_TOUCH_ADJUSTMENT=1 -DENABLE_TOUCH_EVENTS=1 -DENABLE_WEB_SOCKETS=1 -DENABLE_WEB_TIMING=1 -DENABLE_WORKERS=1 -DENABLE_XHR_TIMEOUT=1 -DWTF_USE_TILED_BACKING_STORE=1 -DHAVE_QTQUICK=1 -DHAVE_QTPRINTSUPPORT=1 -DHAVE_QSTYLE=1 -DHAVE_QTTESTLIB=1 -DWTF_USE_LIBXML2=1 -DENABLE_XSLT=1 -DWTF_USE_ZLIB=1 -DWTF_USE_LIBJPEG=1 -DWTF_USE_LIBPNG=1 -DHAVE_XCOMPOSITE=1 -DHAVE_XRENDER=1 -DHAVE_FONTCONFIG=1 -DENABLE_NETSCAPE_PLUGIN_API=1 -DWTF_USE_PLUGIN_BACKEND_XLIB=1 -DPLUGIN_ARCHITECTURE_X11=1 -DENABLE_PLUGIN_PROCESS=1 -DWTF_USE_3D_GRAPHICS=1 -DENABLE_WEBGL=1 -DENABLE_CSS_SHADERS=1 -DENABLE_VIDEO=1 -DWTF_USE_GSTREAMER=1 -DHAVE_SQLITE3=1 -DENABLE_GAMEPAD=1 -DENABLE_TOUCH_SLIDER=1 -DENABLE_ACCELERATED_2D_CANVAS=0 -DENABLE_ANIMATION_API=0 -DENABLE_BATTERY_STATUS=0 -DENABLE_CSP_NEXT=0 -DENABLE_CSS_GRID_LAYOUT=0 -DENABLE_CSS_HIERARCHIES=0 -DENABLE_CSS_IMAGE_ORIENTATION=0 -DENABLE_CSS_IMAGE_RESOLUTION=0 -DENABLE_CSS_VARIABLES=0 -DENABLE_CSS3_BACKGROUND=0 -DENABLE_CSS3_CONDITIONAL_RULES=0 -DENABLE_CSS3_TEXT=0 -DENABLE_DASHBOARD_SUPPORT=0 -DENABLE_DATAGRID=0 -DENABLE_DATA_TRANSFER_ITEMS=0 -DENABLE_DEVICE_ORIENTATION=0 -DENABLE_DIRECTORY_UPLOAD=0 -DENABLE_DOWNLOAD_ATTRIBUTE=0 -DENABLE_FILE_SYSTEM=0 -DENABLE_GEOLOCATION=0 -DENABLE_HIGH_DPI_CANVAS=0 -DENABLE_INDEXED_DATABASE=0 -DENABLE_INPUT_SPEECH=0 -DENABLE_INPUT_TYPE_DATE=0 -DENABLE_INPUT_TYPE_DATETIME=0 -DENABLE_INPUT_TYPE_DATETIMELOCAL=0 -DENABLE_INPUT_TYPE_MONTH=0 -DENABLE_INPUT_TYPE_TIME=0 -DENABLE_INPUT_TYPE_WEEK=0 -DENABLE_LEGACY_CSS_VENDOR_PREFIXES=0 -DENABLE_LINK_PRERENDER=0 -DENABLE_MATHML=0 -DENABLE_MEDIA_SOURCE=0 -DENABLE_MEDIA_STATISTICS=0 -DENABLE_MEDIA_STREAM=0 -DENABLE_MICRODATA=0 -DENABLE_NAVIGATOR_CONTENT_UTILS=0 -DENABLE_NETWORK_INFO=0 -DENABLE_ORIENTATION_EVENTS=0 -DENABLE_PROXIMITY_EVENTS=0 -DENABLE_QUOTA=0 -DENABLE_SCRIPTED_SPEECH=0 -DENABLE_SHADOW_DOM=0 -DENABLE_STYLE_SCOPED=0 -DENABLE_SVG_DOM_OBJC_BINDINGS=0 -DENABLE_TEXT_AUTOSIZING=0 -DENABLE_TEXT_NOTIFICATIONS_ONLY=0 -DENABLE_TOUCH_ICON_LOADING=0 -DENABLE_VIBRATION=0 -DENABLE_VIDEO_TRACK=0 -DENABLE_WEB_AUDIO=0 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_WEBKITWIDGETS_LIB -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_QML_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/qt5/mkspecs/linux-g++ -I. -I../../Source -I../include -I../../include -I../../include/QtWebKitWidgets -I/usr/include/QtQuick -I/usr/include/QtOpenGL -I/usr/include/QtPrintSupport -I/usr/include/QtQml -I../../include/QtWebKit -I/usr/include/QtWidgets -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include/QtCore -I.moc/debug-shared -o .obj/debug-shared/qt/MainQt.o qt/MainQt.cpp
g++ -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-rpath,/mauibuild/source/qtwebkit/_build/lib -Wl,-rpath,/usr/lib -Wl,-rpath-link,/usr/lib -o ../../bin/QtWebProcess .obj/debug-shared/qt/MainQt.o   -L/mauibuild/source/qtwebkit/_build/lib -lQt5WebKitWidgets -lX11 -lxslt -lz -ldl -lm -lrt -lxml2 -ludev -lgio-2.0 -lgstapp-1.0 -lgstpbutils-1.0 -lgstvideo-1.0 -lgstaudio-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lsqlite3 -L/usr/lib -lQt5Sql -lQt5Quick -lQt5OpenGL -lQt5PrintSupport -lQt5Qml -lQt5WebKit -lQt5Widgets -lQt5Network -lQt5Gui -lQt5Core -lGLESv2 -lpthread
/mauibuild/source/qtwebkit/_build/lib/libQt5WebKit.so: undefined reference to `WebCore::FullScreenVideoWindow::keyPressEvent(QKeyEvent*)'
/mauibuild/source/qtwebkit/_build/lib/libQt5WebKit.so: undefined reference to `WebCore::FullScreenVideoWindow::showFullScreen()'
/mauibuild/source/qtwebkit/_build/lib/libQt5WebKit.so: undefined reference to `WebCore::FullScreenVideoWindow::event(QEvent*)'
/mauibuild/source/qtwebkit/_build/lib/libQt5WebKit.so: undefined reference to `WebCore::FullScreenVideoWindow::hideCursor()'
collect2: error: ld returned 1 exit status
make[2]: *** [../../bin/QtWebProcess] Error 1
make[2]: Leaving directory `/mauibuild/source/qtwebkit/_build/Source/WebKit2'
make[1]: *** [sub-WebKit2-WebProcess-pro-make_first-ordered] Error 2
make[1]: Leaving directory `/mauibuild/source/qtwebkit/_build/Source'
make: *** [sub-Source-QtWebKit-pro-make_first-ordered] Error 2
Sun Jul 21 09:24:50 2013 mauibuild-compile-one: FATAL: pid 197 exited with code 2
Sun Jul 21 15:24:50 2013 mauibuild: pid 27734 exited with code 1
Sun Jul 21 15:24:50 2013 mauibuild: FATAL: Build of qtwebkit failed